### ISSUE TITLE
Parser crashes on repealed paragraphs without "(weggefallen)"

### ISSUE THREAD

**Issue by Piratonym** [Drahflow/jura-parse#1]
**Problem:** _§§ 46-49 (Fachliche Voraussetzungen) LuftPersV_ (http://www.gesetze-im-internet.de/luftpersv/#BJNR000530976BJNE008002305) were repealed, but don't have "(weggefallen)" in their title or body. This causes the parser to crash:

```
Parsing data/laws/BJNR000530976.html...
<div class="jnnorm" id="BJNR000530976BJNE008002305" title="Einzelnorm"><div class="jnheader"> <a name="BJNR000530976BJNE008002305"/><a href="index.html#BJNR000530976BJNE008002305">Nichtamtliches Inhaltsverzeichnis</a><h3><span class="jnenbez">§§ 46 bis 49</span> <span class="jnentitel">Fachliche Voraussetzungen</span></h3> </div></div>
§§ 46 bis 49 Fachliche Voraussetzungen
Verordnung über Luftfahrtpersonal
Died at Parse.pm line 372.
```

**Possible solution**: Also check the subsection title (e.g. _LuftPersV "Unterabschnitt 4 (weggefallen)"_) for "(weggefallen)".

**Comment by Drahflow** [comment]
Everything should parse again.
